language: java

addons:
    code_climate:
        repo_token: 2b0e05568065d73f26772b0047ae8d019084c0e8a4e7e9b923a81e0b84ffd044

script:
    ./gradlew check

install: /bin/true

before_script:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)